// Generated by CoffeeScript 1.6.3
/* --------------------------------------------
     Begin scrollToTop.coffee
--------------------------------------------
*/(function(){$(".scrollTop").on("click",function(e){e.preventDefault();return $("html, body").animate({scrollTop:0},800,"easeInOutCubic")})}).call(this);