// Generated by CoffeeScript 1.6.3
(function(){jQuery(function(){console.log("ready");alert("ready");$(".scrollTop").on("click",function(e){e.preventDefault();return $("html, body").animate({scrollTop:0},800,"easeInOutCubic")});return $(".min-read").on("click",function(e){e.preventDefault();return $("article").minRead()})})}).call(this);
